name: Test & Coverage (JaCoCo -> Codecov)

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Build & Test (with JaCoCo)
        run: mvn -B -U -DskipITs=true test -f java/opendataloader-pdf-core/pom.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: java/opendataloader-pdf-core/target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
